//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//

package com.cognizant.cvs.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LineItemType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LineItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drugName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rphId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineItemType", propOrder = { "drugName", "quantity", "rphId" })
public class LineItemType {

	@XmlElement(required = true)
	protected String drugName;
	@XmlElement(required = true)
	protected String quantity;
	@XmlElement(required = true)
	protected String rphId;
	
	protected String orderID;

	public LineItemType(String drugName, String quantity, String rphId,String orderID) {
		super();
		this.drugName = drugName;
		this.quantity = quantity;
		this.rphId = rphId;
		this.orderID = orderID;
	}

	public LineItemType() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getOrderID() {
		return orderID;
	}

	public void setOrderID(String orderID) {
		this.orderID = orderID;
	}

	/**
	 * Gets the value of the drugName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDrugName() {
		return drugName;
	}

	/**
	 * Sets the value of the drugName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDrugName(String value) {
		this.drugName = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setQuantity(String value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the rphId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRphId() {
		return rphId;
	}

	/**
	 * Sets the value of the rphId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRphId(String value) {
		this.rphId = value;
	}

	@Override
	public String toString() {
		return "LineItemType [drugName=" + drugName + ", quantity=" + quantity + ", rphId=" + rphId + ", orderID="
				+ orderID + "]";
	}

}
