//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//


package com.cognizant.cvs.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cognizant.cvs.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RphDetails_QNAME = new QName("http://www.example.org/NewXMLSchema", "rphDetails");
    private final static QName _StoreDetails_QNAME = new QName("http://www.example.org/NewXMLSchema", "storeDetails");
    private final static QName _WorkItemRequest_QNAME = new QName("http://www.example.org/NewXMLSchema", "workItemRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cognizant.cvs.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RPHDetails }
     * 
     */
    public RPHDetails createRPHDetails() {
        return new RPHDetails();
    }

    /**
     * Create an instance of {@link StoreDetails }
     * 
     */
    public StoreDetails createStoreDetails() {
        return new StoreDetails();
    }

    /**
     * Create an instance of {@link WorkItemRequestType }
     * 
     */
    public WorkItemRequestType createWorkItemRequestType() {
        return new WorkItemRequestType();
    }

    /**
     * Create an instance of {@link LineItemType }
     * 
     */
    public LineItemType createLineItemType() {
        return new LineItemType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link RPHWorkQueueType }
     * 
     */
    public RPHWorkQueueType createRPHWorkQueueType() {
        return new RPHWorkQueueType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link WorkItemType }
     * 
     */
    public WorkItemType createWorkItemType() {
        return new WorkItemType();
    }

    /**
     * Create an instance of {@link RPHPDetailType }
     * 
     */
    public RPHPDetailType createRPHPDetailType() {
        return new RPHPDetailType();
    }

    /**
     * Create an instance of {@link StoreDetailType }
     * 
     */
    public StoreDetailType createStoreDetailType() {
        return new StoreDetailType();
    }

    /**
     * Create an instance of {@link PrescriberDetailsType }
     * 
     */
    public PrescriberDetailsType createPrescriberDetailsType() {
        return new PrescriberDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPHDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NewXMLSchema", name = "rphDetails")
    public JAXBElement<RPHDetails> createRphDetails(RPHDetails value) {
        return new JAXBElement<RPHDetails>(_RphDetails_QNAME, RPHDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NewXMLSchema", name = "storeDetails")
    public JAXBElement<StoreDetails> createStoreDetails(StoreDetails value) {
        return new JAXBElement<StoreDetails>(_StoreDetails_QNAME, StoreDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkItemRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NewXMLSchema", name = "workItemRequest")
    public JAXBElement<WorkItemRequestType> createWorkItemRequest(WorkItemRequestType value) {
        return new JAXBElement<WorkItemRequestType>(_WorkItemRequest_QNAME, WorkItemRequestType.class, null, value);
    }

}
