//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//


package com.cognizant.cvs.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prescriberDetails" type="{http://www.example.org/NewXMLSchema}PrescriberDetailsType"/>
 *         &lt;element name="lineItems" type="{http://www.example.org/NewXMLSchema}LineItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderType", propOrder = {
    "orderStatus",
    "orderID",
    "clientID",
    "prescriberDetails",
    "lineItems"
})
public class OrderType {

    @XmlElement(required = true)
    protected String orderStatus;
    @XmlElement(required = true)
    protected String orderID;
    @XmlElement(required = true)
    protected String clientID;
    @XmlElement(required = true)
    protected PrescriberDetailsType prescriberDetails;
    @XmlElement(required = true)
    protected List<LineItemType> lineItems;

    public OrderType(String orderStatus, String orderID, String clientID, PrescriberDetailsType prescriberDetails,
			List<LineItemType> lineItems) {
		super();
		this.orderStatus = orderStatus;
		this.orderID = orderID;
		this.clientID = clientID;
		this.prescriberDetails = prescriberDetails;
		this.lineItems = lineItems;
	}

	public OrderType() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the clientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientID(String value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the prescriberDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PrescriberDetailsType }
     *     
     */
    public PrescriberDetailsType getPrescriberDetails() {
        return prescriberDetails;
    }

    /**
     * Sets the value of the prescriberDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescriberDetailsType }
     *     
     */
    public void setPrescriberDetails(PrescriberDetailsType value) {
        this.prescriberDetails = value;
    }

    /**
     * Gets the value of the lineItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemType }
     * 
     * 
     */
    public List<LineItemType> getLineItems() {
        if (lineItems == null) {
            lineItems = new ArrayList<LineItemType>();
        }
        return this.lineItems;
    }

	@Override
	public String toString() {
		return "OrderType [orderStatus=" + orderStatus + ", orderID=" + orderID + ", clientID=" + clientID
				+ ", prescriberDetails=" + prescriberDetails + ", lineItems=" + lineItems + "]";
	}

}
