//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//


package com.cognizant.cvs.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RPHPDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RPHPDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="certificationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rphBackLog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rphId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rphWorkQueue" type="{http://www.example.org/NewXMLSchema}workItemType" maxOccurs="unbounded"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isEligible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RPHPDetailType", propOrder = {
    "certificationId",
    "rphBackLog",
    "rphId",
    "rphWorkQueue",
    "state",
    "storeId",
    "isEligible"
})
public class RPHPDetailType {

    @XmlElement(required = true)
    protected String certificationId;
    @XmlElement(required = true)
    protected String rphBackLog;
    @XmlElement(required = true)
    protected String rphId;
    @XmlElement(required = true)
    protected List<WorkItemType> rphWorkQueue;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String storeId;
    protected boolean isEligible;

    /**
     * Gets the value of the certificationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationId() {
        return certificationId;
    }

    /**
     * Sets the value of the certificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationId(String value) {
        this.certificationId = value;
    }

    /**
     * Gets the value of the rphBackLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRphBackLog() {
        return rphBackLog;
    }

    /**
     * Sets the value of the rphBackLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRphBackLog(String value) {
        this.rphBackLog = value;
    }

    /**
     * Gets the value of the rphId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRphId() {
        return rphId;
    }

    /**
     * Sets the value of the rphId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRphId(String value) {
        this.rphId = value;
    }

    /**
     * Gets the value of the rphWorkQueue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rphWorkQueue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRphWorkQueue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkItemType }
     * 
     * 
     */
    public List<WorkItemType> getRphWorkQueue() {
        if (rphWorkQueue == null) {
            rphWorkQueue = new ArrayList<WorkItemType>();
        }
        return this.rphWorkQueue;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the storeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * Sets the value of the storeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreId(String value) {
        this.storeId = value;
    }

    /**
     * Gets the value of the isEligible property.
     * 
     */
    public boolean isIsEligible() {
        return isEligible;
    }

    /**
     * Sets the value of the isEligible property.
     * 
     */
    public void setIsEligible(boolean value) {
        this.isEligible = value;
    }

}
