//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//


package com.cognizant.cvs.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workItemID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workItemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workItemStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineItem" type="{http://www.example.org/NewXMLSchema}LineItemType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workItemType", propOrder = {
    "workItemID",
    "workItemType",
    "workItemStatus",
    "lineItem"
})
public class WorkItemType {

    @XmlElement(required = true)
    protected String workItemID;
    @XmlElement(required = true)
    protected String workItemType;
    @XmlElement(required = true)
    protected String workItemStatus;
    @XmlElement(required = true)
    protected LineItemType lineItem;

    /**
     * Gets the value of the workItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkItemID() {
        return workItemID;
    }

    /**
     * Sets the value of the workItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkItemID(String value) {
        this.workItemID = value;
    }

    /**
     * Gets the value of the workItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkItemType() {
        return workItemType;
    }

    /**
     * Sets the value of the workItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkItemType(String value) {
        this.workItemType = value;
    }

    /**
     * Gets the value of the workItemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkItemStatus() {
        return workItemStatus;
    }

    /**
     * Sets the value of the workItemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkItemStatus(String value) {
        this.workItemStatus = value;
    }

    /**
     * Gets the value of the lineItem property.
     * 
     * @return
     *     possible object is
     *     {@link LineItemType }
     *     
     */
    public LineItemType getLineItem() {
        return lineItem;
    }

    /**
     * Sets the value of the lineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineItemType }
     *     
     */
    public void setLineItem(LineItemType value) {
        this.lineItem = value;
    }

}
