//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 08:46:48 PM EST 
//

package com.cognizant.cvs.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WorkItemRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WorkItemRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WorkItemID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkItemStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order" type="{http://www.example.org/NewXMLSchema}OrderType"/>
 *         &lt;element name="NewElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkItemRequestType", propOrder = { "workItemID", "workItemStatus", "order", "newElement" })
public class WorkItemRequestType {

	@XmlElement(name = "WorkItemID", required = true)
	protected String workItemID;
	@XmlElement(name = "WorkItemStatus", required = true)
	protected String workItemStatus;
	@XmlElement(required = true)
	protected OrderType order;
	@XmlElement(name = "NewElement", required = true)
	protected String newElement;

	public WorkItemRequestType(String workItemID, String workItemStatus, OrderType order, String newElement) {
		super();
		this.workItemID = workItemID;
		this.workItemStatus = workItemStatus;
		this.order = order;
		this.newElement = newElement;
	}

	public WorkItemRequestType() {
		super();		
	}

	/**
	 * Gets the value of the workItemID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWorkItemID() {
		return workItemID;
	}

	/**
	 * Sets the value of the workItemID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWorkItemID(String value) {
		this.workItemID = value;
	}

	/**
	 * Gets the value of the workItemStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWorkItemStatus() {
		return workItemStatus;
	}

	/**
	 * Sets the value of the workItemStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWorkItemStatus(String value) {
		this.workItemStatus = value;
	}

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link OrderType }
	 * 
	 */
	public OrderType getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link OrderType }
	 * 
	 */
	public void setOrder(OrderType value) {
		this.order = value;
	}

	/**
	 * Gets the value of the newElement property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNewElement() {
		return newElement;
	}

	/**
	 * Sets the value of the newElement property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNewElement(String value) {
		this.newElement = value;
	}

	@Override
	public String toString() {
		return "WorkItemRequestType [workItemID=" + workItemID + ", workItemStatus=" + workItemStatus + ", order="
				+ order + ", newElement=" + newElement + "]";
	}

}
